/*
 * Copyright (C) 2012 Freescale Semiconductor, Inc. All Rights Reserved.
 * Copyright (C) 2013 Poslab Co. Ltd All Rights Reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#ifndef _BOARD_MX6DL_SAVAGE_H
#define _BOARD_MX6DL_SAVAGE_H
#include <mach/iomux-mx6dl.h>

static iomux_v3_cfg_t mx6dl_savage_pads[] = {
	/* AUDMUX */
	MX6DL_PAD_CSI0_DAT4__AUDMUX_AUD3_TXC,
	MX6DL_PAD_CSI0_DAT5__AUDMUX_AUD3_TXD,
	MX6DL_PAD_CSI0_DAT6__AUDMUX_AUD3_TXFS,
	MX6DL_PAD_CSI0_DAT7__AUDMUX_AUD3_RXD,
	MX6DL_PAD_GPIO_4__GPIO_1_4,		/* AUD INT */

	/* HDMI CEC */
	MX6DL_PAD_KEY_ROW2__HDMI_TX_CEC_LINE,
//	MX6DL_PAD_GPIO_1__WDOG2_WDOG_B,		/*WDOG_B to reset pmic*/

	/* CCM */
	MX6DL_PAD_GPIO_0__CCM_CLKO,		/* sys_mclk */

	/* ECSPI1 */
	MX6DL_PAD_KEY_COL0__ECSPI1_SCLK,
	MX6DL_PAD_KEY_ROW0__ECSPI1_MOSI,
	MX6DL_PAD_KEY_COL1__ECSPI1_MISO,
	MX6DL_PAD_KEY_ROW1__ECSPI1_SS0,
	MX6DL_PAD_KEY_COL2__ECSPI1_SS1,

	/* ENET */
	MX6DL_PAD_ENET_MDIO__ENET_MDIO,
	MX6DL_PAD_ENET_MDC__ENET_MDC,
	MX6DL_PAD_RGMII_TXC__ENET_RGMII_TXC,
	MX6DL_PAD_RGMII_TD0__ENET_RGMII_TD0,
	MX6DL_PAD_RGMII_TD1__ENET_RGMII_TD1,
	MX6DL_PAD_RGMII_TD2__ENET_RGMII_TD2,
	MX6DL_PAD_RGMII_TD3__ENET_RGMII_TD3,
	MX6DL_PAD_RGMII_TX_CTL__ENET_RGMII_TX_CTL,
	MX6DL_PAD_ENET_REF_CLK__ENET_TX_CLK,
	MX6DL_PAD_RGMII_RXC__ENET_RGMII_RXC,
	MX6DL_PAD_RGMII_RD0__ENET_RGMII_RD0,
	MX6DL_PAD_RGMII_RD1__ENET_RGMII_RD1,
	MX6DL_PAD_RGMII_RD2__ENET_RGMII_RD2,
	MX6DL_PAD_RGMII_RD3__ENET_RGMII_RD3,
	MX6DL_PAD_RGMII_RX_CTL__ENET_RGMII_RX_CTL,
	MX6DL_PAD_ENET_CRS_DV__GPIO_1_25,	/* RGMII reset */
	MX6DL_PAD_ENET_RXD1__GPIO_1_26,		/* RGMII Interrupt */
	MX6DL_PAD_ENET_TX_EN__GPIO_1_28,		/* ETH WOL Interrupt */

	/* GPIO2 */
	MX6DL_PAD_EIM_A22__GPIO_2_16,	/* J12 - Boot Mode Select */
	MX6DL_PAD_EIM_A21__GPIO_2_17,	/* J12 - Boot Mode Select */
	MX6DL_PAD_EIM_A20__GPIO_2_18,	/* J12 - Boot Mode Select */
	MX6DL_PAD_EIM_A19__GPIO_2_19,	/* J12 - Boot Mode Select */
	MX6DL_PAD_EIM_A18__GPIO_2_20,	/* J12 - Boot Mode Select */
	MX6DL_PAD_EIM_A17__GPIO_2_21,	/* J12 - Boot Mode Select */
	MX6DL_PAD_EIM_A16__GPIO_2_22,	/* J12 - Boot Mode Select */
	MX6DL_PAD_EIM_RW__GPIO_2_26,	/* J12 - Boot Mode Select */
	MX6DL_PAD_EIM_LBA__GPIO_2_27,	/* J12 - Boot Mode Select */
	MX6DL_PAD_EIM_EB0__GPIO_2_28,	/* J12 - Boot Mode Select */
	MX6DL_PAD_EIM_EB1__GPIO_2_29,	/* J12 - Boot Mode Select */
	MX6DL_PAD_EIM_EB3__GPIO_2_31,	/* J12 - Boot Mode Select */

	/* GPIO3 */
	MX6DL_PAD_EIM_DA0__GPIO_3_0,	/* J12 - Boot Mode Select */
	MX6DL_PAD_EIM_DA1__GPIO_3_1,	/* J12 - Boot Mode Select */
	MX6DL_PAD_EIM_DA2__GPIO_3_2,	/* J12 - Boot Mode Select */
	MX6DL_PAD_EIM_DA3__GPIO_3_3,	/* J12 - Boot Mode Select */
	MX6DL_PAD_EIM_DA4__GPIO_3_4,	/* J12 - Boot Mode Select */
	MX6DL_PAD_EIM_DA5__GPIO_3_5,	/* J12 - Boot Mode Select */
	MX6DL_PAD_EIM_DA6__GPIO_3_6,	/* J12 - Boot Mode Select */
	MX6DL_PAD_EIM_DA7__GPIO_3_7,	/* J12 - Boot Mode Select */
	MX6DL_PAD_EIM_DA8__GPIO_3_8,	/* J12 - Boot Mode Select */
	MX6DL_PAD_EIM_DA9__GPIO_3_9,	/* J12 - Boot Mode Select */
	MX6DL_PAD_EIM_DA10__GPIO_3_10,	/* J12 - Boot Mode Select */
	MX6DL_PAD_EIM_DA11__GPIO_3_11,	/* J12 - Boot Mode Select */
	MX6DL_PAD_EIM_DA12__GPIO_3_12,	/* J12 - Boot Mode Select */
	MX6DL_PAD_EIM_DA13__GPIO_3_13,	/* J12 - Boot Mode Select */
	MX6DL_PAD_EIM_DA14__GPIO_3_14,	/* J12 - Boot Mode Select */
	MX6DL_PAD_EIM_DA15__GPIO_3_15,	/* J12 - Boot Mode Select */

	/* GPIO5 */
	MX6DL_PAD_EIM_WAIT__GPIO_5_0,	/* J12 - Boot Mode Select */
	MX6DL_PAD_EIM_A24__GPIO_5_4,	/* J12 - Boot Mode Select */

	/* GPIO6 */
	MX6DL_PAD_EIM_A23__GPIO_6_6,	/* J12 - Boot Mode Select */

	/* I2C1, WM8326,WM8903 */
	MX6DL_PAD_CSI0_DAT8__I2C1_SDA,
	MX6DL_PAD_CSI0_DAT9__I2C1_SCL,

	/* I2C2, Camera, MIPI */
	MX6DL_PAD_KEY_COL3__I2C2_SCL,
	MX6DL_PAD_KEY_ROW3__I2C2_SDA,

	/* I2C3 */
	MX6DL_PAD_GPIO_3__I2C3_SCL,
	MX6DL_PAD_GPIO_6__I2C3_SDA,

	/* DISP_PWM */
	MX6DL_PAD_SD1_DAT3__PWM1_PWMO,		/* GPIO1[21] */
	MX6DL_PAD_SD1_DAT1__PWM3_PWMO,		/* GPIO1[17] */
	MX6DL_PAD_SD1_CMD__PWM4_PWMO,		/* GPIO1[18] */

	/* UART1 for debug */
	MX6DL_PAD_CSI0_DAT10__UART1_TXD,
	MX6DL_PAD_CSI0_DAT11__UART1_RXD,
	MX6DL_PAD_EIM_D19__UART1_CTS,
	MX6DL_PAD_EIM_D20__UART1_RTS,

	/* UART2 */
	MX6DL_PAD_EIM_D26__UART2_TXD,
	MX6DL_PAD_EIM_D27__UART2_RXD,
	MX6DL_PAD_EIM_D28__UART2_CTS,
	MX6DL_PAD_EIM_D29__UART2_RTS,

	/* UART3 */
	MX6DL_PAD_EIM_D24__UART3_TXD,
	MX6DL_PAD_EIM_D25__UART3_RXD,
	MX6DL_PAD_EIM_D23__UART3_CTS,
	MX6DL_PAD_EIM_D31__UART3_RTS,

	/* USBOTG ID pin */
	MX6DL_PAD_ENET_RX_ER__ANATOP_USBOTG_ID,

	/* USDHC2 */
	MX6DL_PAD_SD2_CLK__USDHC2_CLK,
	MX6DL_PAD_SD2_CMD__USDHC2_CMD,
	MX6DL_PAD_SD2_DAT0__USDHC2_DAT0,
	MX6DL_PAD_SD2_DAT1__USDHC2_DAT1,
	MX6DL_PAD_SD2_DAT2__USDHC2_DAT2,
	MX6DL_PAD_SD2_DAT3__USDHC2_DAT3,

	/* USDHC3 */
	MX6DL_PAD_SD3_CLK__USDHC3_CLK_50MHZ,
	MX6DL_PAD_SD3_CMD__USDHC3_CMD_50MHZ,
	MX6DL_PAD_SD3_DAT0__USDHC3_DAT0_50MHZ,
	MX6DL_PAD_SD3_DAT1__USDHC3_DAT1_50MHZ,
	MX6DL_PAD_SD3_DAT2__USDHC3_DAT2_50MHZ,
	MX6DL_PAD_SD3_DAT3__USDHC3_DAT3_50MHZ,
	MX6DL_PAD_NANDF_D0__GPIO_2_0,		/* SD3_CD */

	/* USDHC4 */
	MX6DL_PAD_SD4_CLK__USDHC4_CLK_50MHZ,
	MX6DL_PAD_SD4_CMD__USDHC4_CMD_50MHZ,
	MX6DL_PAD_SD4_DAT0__USDHC4_DAT0_50MHZ,
	MX6DL_PAD_SD4_DAT1__USDHC4_DAT1_50MHZ,
	MX6DL_PAD_SD4_DAT2__USDHC4_DAT2_50MHZ,
	MX6DL_PAD_SD4_DAT3__USDHC4_DAT3_50MHZ,
	MX6DL_PAD_SD4_DAT4__USDHC4_DAT4_50MHZ,
	MX6DL_PAD_SD4_DAT5__USDHC4_DAT5_50MHZ,
	MX6DL_PAD_SD4_DAT6__USDHC4_DAT6_50MHZ,
	MX6DL_PAD_SD4_DAT7__USDHC4_DAT7_50MHZ,

	/* PCIE */
	MX6DL_PAD_CSI0_DATA_EN__GPIO_5_20,	/* PCIE_WAK */
	MX6DL_PAD_GPIO_17__GPIO_7_12,	/* PCIE_RST */
	MX6DL_PAD_KEY_COL4__GPIO_4_14,	/* PCIE_DIS */

	MX6DL_PAD_GPIO_2__GPIO_1_2,	/*  */
	MX6DL_PAD_GPIO_9__GPIO_1_9,	/*  */

	MX6DL_PAD_NANDF_CS2__GPIO_6_15,	/* LVDS0_EN */
	MX6DL_PAD_NANDF_CS3__GPIO_6_16,	/* LVDS1_EN */
	MX6DL_PAD_SD3_DAT7__GPIO_6_17,	/*  */
	MX6DL_PAD_SD3_DAT6__GPIO_6_18,	/*  */

	MX6DL_PAD_SD3_DAT5__GPIO_7_0,	/*  */
	MX6DL_PAD_SD3_DAT4__GPIO_7_1,	/*  */
	MX6DL_PAD_GPIO_18__GPIO_7_13,	/* PMIC INT */
};

static iomux_v3_cfg_t mx6dl_savage_csi0_sensor_pads[] = {
	/* IPU1 Camera */
	MX6DL_PAD_CSI0_DAT12__IPU1_CSI0_D_12,
	MX6DL_PAD_CSI0_DAT13__IPU1_CSI0_D_13,
	MX6DL_PAD_CSI0_DAT14__IPU1_CSI0_D_14,
	MX6DL_PAD_CSI0_DAT15__IPU1_CSI0_D_15,
	MX6DL_PAD_CSI0_DAT16__IPU1_CSI0_D_16,
	MX6DL_PAD_CSI0_DAT17__IPU1_CSI0_D_17,
	MX6DL_PAD_CSI0_DAT18__IPU1_CSI0_D_18,
	MX6DL_PAD_CSI0_DAT19__IPU1_CSI0_D_19,
	MX6DL_PAD_CSI0_DATA_EN__IPU1_CSI0_DATA_EN,
	MX6DL_PAD_CSI0_MCLK__IPU1_CSI0_HSYNC,
	MX6DL_PAD_CSI0_PIXCLK__IPU1_CSI0_PIXCLK,
	MX6DL_PAD_CSI0_VSYNC__IPU1_CSI0_VSYNC,

	MX6DL_PAD_GPIO_0__CCM_CLKO,		/* camera clk */

	MX6DL_PAD_GPIO_7__GPIO_1_7,		/* camera PWDN */
	MX6DL_PAD_GPIO_8__GPIO_1_8,		/* camera RESET */
};

static iomux_v3_cfg_t mx6dl_savage_mipi_sensor_pads[] = {
	MX6DL_PAD_GPIO_0__CCM_CLKO,		/* camera clk */

	MX6DL_PAD_NANDF_CS0__GPIO_6_11,		/* MIPI_DSI_RST */
	MX6DL_PAD_NANDF_CS1__GPIO_6_14,		/* MIPI_DSI_EN */

	MX6DL_PAD_GPIO_5__GPIO_1_5,		/* CSI_PWN */
	MX6DL_PAD_SD1_CLK__GPIO_1_20,		/* camera RESET */
};

static iomux_v3_cfg_t mx6dl_savage_hdmi_ddc_pads[] = {
	MX6DL_PAD_KEY_COL3__HDMI_TX_DDC_SCL, /* HDMI DDC SCL */
	MX6DL_PAD_KEY_ROW3__HDMI_TX_DDC_SDA, /* HDMI DDC SDA */
};

static iomux_v3_cfg_t mx6dl_savage_i2c2_pads[] = {
	MX6DL_PAD_KEY_COL3__I2C2_SCL,	/* I2C2 SCL */
	MX6DL_PAD_KEY_ROW3__I2C2_SDA,	/* I2C2 SDA */
};
#endif
